FROM bowmanhan/gecko_builder:base
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-distutils python3-apt \
    curl wget git mercurial diffutils vim build-essential libpython3-dev m4 unzip uuid zip \
    python3-dev \
    libssl-dev \
    libffi-dev \
    python3-setuptools \
    python3-wheel \
    python3-cffi \
    sudo ccache libtinfo5 libncurses5 libxml2-dev
WORKDIR /home/bowman