name: Sync dockerhub image to github
run-name: ${{ github.actor }} is sync docker image 🚀
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /usr/share/dotnet
      - run: sudo rm -rf /usr/local/lib/android
      - run: sudo rm -rf /opt/ghc
      - run: sudo rm -rf /usr/local/share/edge_driver /usr/local/share/chrome_driver
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull bowmanhan/gecko_builder:latest
      - run: docker tag bowmanhan/gecko_builder:latest ghcr.io/${{ github.actor }}/gecko_builder:latest
      - run: docker push ghcr.io/${{ github.actor }}/gecko_builder:latest
  notify:
    if: cancelled() == false
    needs: sync-image
    runs-on: ubuntu-latest
    steps:
      - uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.deploy.result }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}