name: pull image test
run-name: ${{ github.actor }} is pulling docker image 🚀
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /usr/share/dotnet
      - run: sudo rm -rf /usr/local/lib/android
      - run: sudo rm -rf /opt/ghc
      - run: sudo rm -rf /usr/local/share/edge_driver /usr/local/share/chrome_driver
      - name: pull image test
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/${{ github.actor }}/gecko_builder:latest
      - run: docker pull bowmanhan/gecko_builder:latest
